services:
  - type: web
    name: mechara-bus-middleware
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: BODS_API_KEY
        sync: false
